name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ main ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.actor == github.repository_owner && github.event_name == 'push' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build/Publish Dockerfile (testing)
      if: github.ref != 'refs/heads/main' || github.actor != github.repository_owner || github.event_name == 'pull_request'
      timeout-minutes: 360
      run: |
            set -x
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" \
            --build-arg maintainer=${{ github.repository_owner }} \
            --file Dockerfile . \
            --tag ghcr.io/${{ github.repository_owner }}/qbittorrent-docker-ratio-faker/qbittorrent-docker-ratio-faker-testing:latest

    - name: Build/Publish Dockerfile (main)
      if: success() && github.ref == 'refs/heads/main' && github.actor == github.repository_owner && github.event_name == 'push'
      timeout-minutes: 360
      run: |
            set -x
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 \
            --output "type=image,push=true" \
            --build-arg maintainer=${{ github.repository_owner }} \
            --file Dockerfile . \
            --tag ghcr.io/${{ github.repository_owner }}/qbittorrent-docker-ratio-faker/qbittorrent-docker-ratio-faker:latest
